### ISSUE TITLE
changing color on moderately large objects stalls the entire UI and does not finish the job

### ISSUE THREAD

**Issue by axtimwalde** [saalfeldlab/bigcat#50] opened 2017-12-21 20:22 UTC
the object ends up dual color in the viewer, no exceptions are thrown

**Comment by hanslovsky** [comment] 2018-01-29 23:06
Duplicate of #49 and will hopefully be obsolete once cached (multiscale) 3D rendering (#63) is available.

**Closed as completed by hanslovsky** 2018-01-29 23:06 UTC
